### ISSUE TITLE
Script and GUI for Load Games Windows 

### ISSUE THREAD

**Issue by EmulationChannel** [SysRay/psOff_public#10]
Script load games Windows requests a very complicated method of running PC games

**Comment by SysRay** [comment]
Sure, I'll add something later (low prio) that creates links. Click it and play.

**Comment by EmulationChannel** [comment]
> Sure, I'll add something later (low prio) that creates links. Click it and play.

Yes Thanks !!! link Discord Project

**Comment by SysRay** [comment]
It's the discord icon, top of the readme. I'll make it more clear.

**Comment by EmulationChannel** [comment]
link not open discord kkkkkkk

**Comment by Hrodgaer** [comment]
1- Create a txt (Notepad) file
2- Add this line:
    emulator.exe --file="Your-ps4-dumped-game-folder\eboot.bin"
3- Save it and change file extension from txt to bat (you can make many bat files for multiple different games)
4- Execute it (If a permission window appear, chose "Permit"

**Comment by SysRay** [comment]
GUI is in the making. 
In the meantime: [Game Link Creator](https://github.com/ChristianStrau/psOFF-GUI )
