### ISSUE TITLE
ngs2 Audio

### ISSUE THREAD

**Issue by SysRay** [SysRay/psOff_public#183]
- [ ] #217
- [ ] #218

**Comment by igor725** [comment]
There are list of games that requires libSceNgs2 implementation (as of 06/02/2024):
SysRay/psOff_compatibility#26
SysRay/psOff_compatibility#27
SysRay/psOff_compatibility#30
SysRay/psOff_compatibility#53
SysRay/psOff_compatibility#54
SysRay/psOff_compatibility#55
SysRay/psOff_compatibility#57
SysRay/psOff_compatibility#58
SysRay/psOff_compatibility#59
SysRay/psOff_compatibility#62
SysRay/psOff_compatibility#66
SysRay/psOff_compatibility#70
SysRay/psOff_compatibility#90
SysRay/psOff_compatibility#91
SysRay/psOff_compatibility#120
SysRay/psOff_compatibility#150
SysRay/psOff_compatibility#157
SysRay/psOff_compatibility#168
SysRay/psOff_compatibility#172
SysRay/psOff_compatibility#173
SysRay/psOff_compatibility#192
SysRay/psOff_compatibility#243
SysRay/psOff_compatibility#244
SysRay/psOff_compatibility#245
SysRay/psOff_compatibility#247
SysRay/psOff_compatibility#248
SysRay/psOff_compatibility#251
SysRay/psOff_compatibility#273
SysRay/psOff_compatibility#274
SysRay/psOff_compatibility#275
SysRay/psOff_compatibility#276
SysRay/psOff_compatibility#302
SysRay/psOff_compatibility#304
