### ISSUE TITLE
Black screen with audio on Nvidia GPU

### ISSUE THREAD

**Issue by Brutal-sam** [SysRay/psOff_public#21]
in the previous release the emulator opens a window and closes immediately on nvidia, it didn't work, but now in beta 0.3 it opens a black screen with audio, runs sonic with good audio no stutter but no graphics, it's a black screen.
munmap unknown 0x4a770000 0x00010000

https://github.com/SysRay/psOff_public/assets/94696121/c16b5374-44c2-4c62-8823-f53af998928b

**Comment by SysRay** [comment]
Thanks for reporting this. Could you please provide the console output aswell?

**Comment by Brutal-sam** [comment]
![Capture](https://github.com/SysRay/psOff_public/assets/94696121/b29c9d34-2123-48b4-93af-7b198666c38d)

**Comment by Hrodgaer** [comment]
Same error

**Comment by SysRay** [comment]
We have included log files with v.0.4
If you want to retest, you can find them in the emulator folder under P7logs/

Please start the game with --vkValidation and include the zipped log.

**Comment by SysRay** [comment]
Inactivity
