### ISSUE TITLE
crash| emulator crashing randomly

### ISSUE THREAD

**Issue by kr1spy2115** [SysRay/psOff_public#242]

**Comment by kr1spy2115** [comment]
Cuphead when no configuration files found in configs folder:

> ExceptionHandler| Error:offset:0x0004d7a4        base:0x11960000        libc.prx
> ExceptionHandler| Critical Error:Access violation: Read at addr:0x119ad7a4 info:0xffffffffffffffff , module base:0x11960000 libc.prx

**Comment by igor725** [comment]
Is Cuphead only affected game? Can't reproduce it with others

**Comment by kr1spy2115** [comment]
> Is Cuphead only affected game? Can't reproduce it with others

maybe, can't find if its only related to specific config file cuz it seems to be crashing randomly by deleting 1 file, sometimes it launches fine without that config, sometimes it crashes
