### ISSUE TITLE
Missing symbol

### ISSUE THREAD

**Issue by Hermiten** [SysRay/psOff_public#6]
Hi,

I tried to lauch Quake (CUSA 24593) but there is a problem with the symbol:

> Selected GPU:AMD Radeon(TM) Graphics api:1.3
> 0x1400186e8
> 0x140015402
> 0x14000e161
> 0x20031ebd        in libc.prx
> Missing Symbol| Name:-o5uEDpN+oY#A#B Lib:libkernel(ver:1) Mod:libkernel(major:1 minor:1)

And then crash

**Comment by Hermiten** [comment]
With the game Jackal Assault (CUSA 06828):

> Selected GPU:AMD Radeon(TM) Graphics api:1.3
> Couldn't Allocate GPU Memory: 0x7fff0000|2147483648 type:51 result:VK_ERROR_OUT_OF_DEVICE_MEMORY
> Map| Couldn't allocHeap vaddr:0x00000000 physAddr:0x00000001 len:0x80000000 prot:0x33 -> out:0x7fff0000
> Kernel: sceKernelMapDirectMemory failed with 0x8001ffea
> Kernel: Argument Count = 1Arg 0 = psOff
> Kernel: ********** LAUNCHER CONTROL ************************************
> Kernel:         File System Root = NONE SPECIFIED
> Kernel:         Launcher Path = NONE SPECIFIED
> Kernel:         Launcher Arguments NONE SPECIFIED
> Kernel: **********/LAUNCHER CONTROL ************************************
> 0x1400186e8
> 0x140015402
> 0x14000e161
> 0x10cb1820        in eboot.bin
> Missing Symbol| Name:IuxnUuXk6Bg#h#N Lib:libkernel(ver:1) Mod:libkernel(major:1 minor:1)

**Comment by gitnewcomer** [comment]
@Hermiten did you read the README from this project before opening this issue?
It clearly states that this is in early development:

**In development. Does it run ...? No!**

The developer knows that the majority of games don't run...

**Comment by SysRay** [comment]
Thanks for your support. We'll create a separate repository for all games related issues, including missing symbols, where testers can create issues and see the current compatibility state.

Issues relating to the emulator itself can be issued here, like sound or gamepad issues. Will be made clear when everything is setup.
