### ISSUE TITLE
Next Features| v.0.5-beta

### ISSUE THREAD

**Issue by SysRay** [SysRay/psOff_public#61]
- [x]  better NVIDIA compatibility
- [x] Shader: Support for for-loops
- [x] Move runtime and main.cpp to public
- [x] "We are doomed"
~~[libSceNgs2]~~ Will be tracked separately.

**Comment by Reynanaldo** [comment]
Como puedo instalar la v 5.0

**Comment by kr1spy2115** [comment]
> Como puedo instalar la v 5.0

You can't yet, wait for release.
