### ISSUE TITLE
Impossible to close emulator.exe windows

### ISSUE THREAD

**Issue by Hermiten** [SysRay/psOff_public#7]
Hi,

When I launch a game like Sonic Mania, it work.
But when I want to close it (to close the windows) it doesn't work and stay like this. I need to use the task manager to force it to close :/

Thanks you

**Comment by SysRay** [comment]
strg+c in the console. I sadly added a bug in the videoout file that should handle the closing. Will be fixed.

**Comment by SysRay** [comment]
Closing the window will exit the emulator now

**Comment by Hrodgaer** [comment]
I've tried the latest version published here (v0.2-beta) and this doesn't work. I had to close the application through the task manager

**Comment by Hermiten** [comment]
> I've tried the latest version published here (v0.2-beta) and this doesn't work. I had to close the application through the task manager

You have to download the last one on "Actions" tab at the top and not on the "Release" one at the right side
Anyway it's fixed but not really available

**Comment by Hrodgaer** [comment]
Ah, ok, thanks!
